#!/usr/bin/env bash
set -euo pipefail

gitleaks git --pre-commit --redact --staged --verbose

if git diff --cached --name-only --diff-filter=ACMR | grep -Eq '\.tf$'; then
  terraform fmt -check -recursive
fi
